# Generated by Django 4.1.7 on 2023-02-20 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_add_mass_model"),
        ("system", "0002_add_galaxy_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="galaxy",
            name="mass",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.mass",
                verbose_name="Mass",
            ),
        ),
        migrations.AddField(
            model_name="planetarysystem",
            name="mass",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.mass",
                verbose_name="Mass",
            ),
        ),
    ]
