# Generated by Django 4.1.7 on 2023-02-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0004_remove_unnecessary_verbose_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="galaxy",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="systems/"),
        ),
        migrations.AddField(
            model_name="planetarysystem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="systems/"),
        ),
    ]
