# Generated by Django 4.1.7 on 2023-02-20 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("system", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Star",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("radius", models.PositiveIntegerField(verbose_name="Radius (km)")),
                (
                    "surface_temperature",
                    models.BigIntegerField(
                        verbose_name="Temperature of the surface (Kelvin)"
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("o", "O"),
                            ("b", "B"),
                            ("a", "A"),
                            ("f", "F"),
                            ("g", "G"),
                            ("k", "K"),
                            ("m", "M"),
                        ],
                        max_length=255,
                        verbose_name="Classification",
                    ),
                ),
                (
                    "distance_from_earth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.distance",
                        verbose_name="Distance from Earth",
                    ),
                ),
                (
                    "planetary_system",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stars",
                        to="system.planetarysystem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("radius", models.PositiveIntegerField(verbose_name="Radius (km)")),
                (
                    "surface_temperature",
                    models.BigIntegerField(
                        verbose_name="Temperature of the surface (Kelvin)"
                    ),
                ),
                (
                    "distance_from_earth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.distance",
                        verbose_name="Distance from Earth",
                    ),
                ),
                (
                    "planetary_system",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planets",
                        to="system.planetarysystem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
