# Generated by Django 4.1.7 on 2023-02-20 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_add_mass_model"),
        ("astronomical_object", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planet",
            name="mass",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.mass",
                verbose_name="Mass",
            ),
        ),
        migrations.AddField(
            model_name="star",
            name="mass",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.mass",
                verbose_name="Mass",
            ),
        ),
    ]
