# Generated by Django 4.1.7 on 2023-02-18 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("astronomical_object", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planet",
            old_name="distanceFromEarth",
            new_name="distance_from_earth",
        ),
        migrations.RenameField(
            model_name="star",
            old_name="distanceFromEarth",
            new_name="distance_from_earth",
        ),
    ]
