# Generated by Django 4.1.7 on 2023-02-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("astronomical_object", "0001_initial"),
        ("common", "0002_planetarysystem"),
    ]

    operations = [
        migrations.AddField(
            model_name="planet",
            name="planetary_system",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.planetarysystem",
            ),
        ),
    ]
