# Generated by Django 4.1.7 on 2023-02-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_planetarysystem"),
        ("astronomical_object", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planet",
            name="distanceFromEarth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.distance",
                verbose_name="Distance from Earth",
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="surface_temperature",
            field=models.PositiveIntegerField(
                verbose_name="Temperature of the surface (Kelvin)"
            ),
        ),
        migrations.AlterField(
            model_name="star",
            name="distanceFromEarth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.distance",
                verbose_name="Distance from Earth",
            ),
        ),
        migrations.AlterField(
            model_name="star",
            name="surface_temperature",
            field=models.PositiveIntegerField(
                verbose_name="Temperature of the surface (Kelvin)"
            ),
        ),
    ]
