# Generated by Django 4.1.7 on 2023-02-20 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_remove_unnecessary_verbose_name"),
        ("astronomical_object", "0002_add_mass_field_to_object"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planet",
            name="distance_from_earth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.distance",
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="mass",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.mass",
            ),
        ),
        migrations.AlterField(
            model_name="planet",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="star",
            name="classification",
            field=models.CharField(
                choices=[
                    ("o", "O"),
                    ("b", "B"),
                    ("a", "A"),
                    ("f", "F"),
                    ("g", "G"),
                    ("k", "K"),
                    ("m", "M"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="star",
            name="distance_from_earth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.distance",
            ),
        ),
        migrations.AlterField(
            model_name="star",
            name="mass",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="common.mass",
            ),
        ),
        migrations.AlterField(
            model_name="star",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
