# Generated by Django 4.1.7 on 2023-02-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Distance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Value")),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[("km", "Kilometre"), ("ly", "Light Year")],
                        default="ly",
                        max_length=255,
                        verbose_name="Unit of measure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanetarySystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
        ),
    ]
