# Generated by Django 4.1.7 on 2023-02-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Value")),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[("kg", "kilogram"), ("M☉", "solar mass")],
                        default="kg",
                        max_length=255,
                        verbose_name="Unit of measure",
                    ),
                ),
            ],
        ),
    ]
