# Generated by Django 4.1.7 on 2023-02-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("astronomical_object", "0003_alter_planet_distancefromearth_and_more"),
        ("common", "0002_planetarysystem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planetarysystem",
            name="star",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planetary_system",
                to="astronomical_object.star",
                verbose_name="Star",
            ),
        ),
    ]
